// categories.config.ts — Source de vérité unique Sokoul
// Toute modification ici se propage sur tout le site

export type CategoryType     = 'genre' | 'keyword' | 'language' | 'era' | 'combo';
export type TimeOfDay        = 'morning' | 'afternoon' | 'evening' | 'night' | 'late-night';
export type Season           = 'spring' | 'summer' | 'autumn' | 'winter';
export type DayType          = 'weekday' | 'weekend';
export type ContentTypeScope = 'movie' | 'series' | 'both';

export interface Category {
  id:           string;
  label:        string;
  emoji:        string;
  type:         CategoryType;
  contentType:  ContentTypeScope;
  params:       Record<string, string>;
  group:        string;
  weight:       number;
  tagline:      string;
  accentColor?: string;
  timeOfDay?:   TimeOfDay[];
  dayOfWeek?:   DayType[];
  seasons?:     Season[];
  featured?:    boolean;
  showInNav?:   boolean;
}

export const CATEGORIES: Category[] = [

  {
    id: 'action', label: 'Action', emoji: '⚡',
    type: 'genre', contentType: 'movie',
    params: { genre: '28' }, group: 'films', weight: 1,
    tagline: 'Adrénaline garantie ou remboursé.',
    accentColor: '#e63946', featured: true, showInNav: true,
    timeOfDay: ['afternoon', 'evening'],
  },
  {
    id: 'aventure', label: 'Aventure', emoji: '🧭',
    type: 'genre', contentType: 'movie',
    params: { genre: '12' }, group: 'films', weight: 2,
    tagline: 'Chaque voyage commence par une première image.',
    accentColor: '#f39c12', featured: true, showInNav: true,
    timeOfDay: ['afternoon', 'evening'],
  },
  {
    id: 'scifi', label: 'Science-Fiction', emoji: '🚀',
    type: 'genre', contentType: 'movie',
    params: { genre: '878' }, group: 'films', weight: 3,
    tagline: "Des futurs que tu n'aurais jamais imaginés.",
    accentColor: '#4361ee', featured: true, showInNav: true,
  },
  {
    id: 'horreur', label: 'Horreur', emoji: '👻',
    type: 'genre', contentType: 'movie',
    params: { genre: '27' }, group: 'films', weight: 4,
    tagline: 'Pour les nuits où tu veux pas dormir.',
    accentColor: '#8b0000', featured: true, showInNav: true,
    timeOfDay: ['night', 'late-night'],
  },
  {
    id: 'thriller', label: 'Thriller', emoji: '👁️',
    type: 'genre', contentType: 'movie',
    params: { genre: '53' }, group: 'films', weight: 5,
    tagline: "La peur ne vient pas toujours de là où on l'attend.",
    accentColor: '#c0392b', featured: true, showInNav: true,
    timeOfDay: ['evening', 'night'],
  },
  {
    id: 'fantastique', label: 'Fantastique', emoji: '✨',
    type: 'genre', contentType: 'movie',
    params: { genre: '14' }, group: 'films', weight: 6,
    tagline: 'Des mondes où tout est possible.',
    accentColor: '#8e44ad', featured: true, showInNav: true,
  },
  {
    id: 'crime', label: 'Crime', emoji: '🔫',
    type: 'genre', contentType: 'movie',
    params: { genre: '80' }, group: 'films', weight: 7,
    tagline: 'Le pouvoir. La trahison. Les conséquences.',
    accentColor: '#2c3e50', featured: true, showInNav: true,
    timeOfDay: ['evening', 'night'],
  },
  {
    id: 'drame', label: 'Drame', emoji: '🎭',
    type: 'genre', contentType: 'movie',
    params: { genre: '18' }, group: 'films', weight: 8,
    tagline: 'Des histoires qui restent.',
    accentColor: '#8e44ad', featured: true, showInNav: true,
  },
  {
    id: 'comedie', label: 'Comédie', emoji: '😂',
    type: 'genre', contentType: 'movie',
    params: { genre: '35' }, group: 'films', weight: 9,
    tagline: 'Parce que rire ça fait du bien.',
    accentColor: '#f4d03f', featured: true, showInNav: true,
    timeOfDay: ['morning', 'afternoon', 'evening'],
    dayOfWeek: ['weekend'],
  },
  {
    id: 'romance', label: 'Romance', emoji: '❤️',
    type: 'genre', contentType: 'movie',
    params: { genre: '10749' }, group: 'films', weight: 10,
    tagline: 'Pour croire encore aux happy endings.',
    accentColor: '#e91e8c', featured: false, showInNav: true,
    timeOfDay: ['evening'],
    dayOfWeek: ['weekend'],
  },
  {
    id: 'animation', label: 'Animation', emoji: '🎨',
    type: 'genre', contentType: 'movie',
    params: { genre: '16' }, group: 'films', weight: 11,
    tagline: 'Les plus belles histoires ne sont pas toujours réelles.',
    accentColor: '#ff9f43', featured: true, showInNav: true,
    timeOfDay: ['morning', 'afternoon'],
  },
  {
    id: 'famille', label: 'Famille', emoji: '👨‍👩‍👧',
    type: 'genre', contentType: 'movie',
    params: { genre: '10751' }, group: 'films', weight: 12,
    tagline: 'Pour regarder ensemble, sans exception.',
    accentColor: '#e84393', featured: false, showInNav: true,
    timeOfDay: ['afternoon'],
    dayOfWeek: ['weekend'],
  },
  {
    id: 'documentaire', label: 'Documentaire', emoji: '🎬',
    type: 'genre', contentType: 'movie',
    params: { genre: '99' }, group: 'films', weight: 13,
    tagline: 'La réalité est plus folle que la fiction.',
    accentColor: '#2ecc71', featured: true, showInNav: true,
    timeOfDay: ['morning', 'afternoon'],
  },
  {
    id: 'histoire', label: 'Histoire', emoji: '📜',
    type: 'genre', contentType: 'movie',
    params: { genre: '36' }, group: 'films', weight: 14,
    tagline: "Ce qui s'est passé mérite d'être vu.",
    accentColor: '#1a5276', featured: false, showInNav: true,
    timeOfDay: ['afternoon', 'evening'],
  },
  {
    id: 'mystere', label: 'Mystère', emoji: '🔍',
    type: 'genre', contentType: 'movie',
    params: { genre: '9648' }, group: 'films', weight: 15,
    tagline: 'Tu pensais avoir trouvé. Tu avais tort.',
    accentColor: '#6c3483', featured: false, showInNav: true,
    timeOfDay: ['evening', 'night'],
  },
  {
    id: 'musique', label: 'Musique', emoji: '🎵',
    type: 'genre', contentType: 'movie',
    params: { genre: '10402' }, group: 'films', weight: 16,
    tagline: 'Quand les images chantent.',
    accentColor: '#1db954', featured: false, showInNav: false,
  },
  {
    id: 'guerre', label: 'Guerre', emoji: '⚔️',
    type: 'genre', contentType: 'movie',
    params: { genre: '10752' }, group: 'films', weight: 17,
    tagline: 'Les vraies histoires de ceux qui sont tombés.',
    accentColor: '#7f8c8d', featured: false, showInNav: true,
  },
  {
    id: 'western', label: 'Western', emoji: '🤠',
    type: 'genre', contentType: 'movie',
    params: { genre: '37' }, group: 'films', weight: 18,
    tagline: 'Justice, poussière et soleil couchant.',
    accentColor: '#a04000', featured: false, showInNav: true,
  },

  {
    id: 'series-action', label: 'Séries Action', emoji: '⚡',
    type: 'genre', contentType: 'series',
    params: { genre: '10759' }, group: 'series', weight: 1,
    tagline: 'Le suspense épisode après épisode.',
    accentColor: '#e63946', featured: true, showInNav: true,
    timeOfDay: ['evening', 'night'],
  },
  {
    id: 'series-scifi', label: 'Séries Sci-Fi & Fantasy', emoji: '🚀',
    type: 'genre', contentType: 'series',
    params: { genre: '10765' }, group: 'series', weight: 2,
    tagline: "Des univers qui s'étendent sur des saisons entières.",
    accentColor: '#4361ee', featured: true, showInNav: true,
  },
  {
    id: 'series-crime', label: 'Séries Crime', emoji: '🔫',
    type: 'genre', contentType: 'series',
    params: { genre: '80' }, group: 'series', weight: 3,
    tagline: 'On commence un épisode. On en regarde dix.',
    accentColor: '#2c3e50', featured: true, showInNav: true,
    timeOfDay: ['evening', 'night'],
  },
  {
    id: 'series-drame', label: 'Séries Drame', emoji: '🎭',
    type: 'genre', contentType: 'series',
    params: { genre: '18' }, group: 'series', weight: 4,
    tagline: "Des personnages qu'on n'oublie jamais.",
    accentColor: '#8e44ad', featured: true, showInNav: true,
  },
  {
    id: 'series-comedie', label: 'Séries Comédie', emoji: '😂',
    type: 'genre', contentType: 'series',
    params: { genre: '35' }, group: 'series', weight: 5,
    tagline: 'Pour les soirées où on veut juste sourire.',
    accentColor: '#f4d03f', featured: true, showInNav: true,
    timeOfDay: ['evening'],
    dayOfWeek: ['weekend'],
  },
  {
    id: 'series-anime', label: 'Animés', emoji: '🗾',
    type: 'genre', contentType: 'series',
    params: { genre: '16' }, group: 'series', weight: 6,
    tagline: "L'animation japonaise a réinventé la narration.",
    accentColor: '#e74c3c', featured: true, showInNav: true,
  },
  {
    id: 'series-mystere', label: 'Séries Mystère', emoji: '🔍',
    type: 'genre', contentType: 'series',
    params: { genre: '9648' }, group: 'series', weight: 7,
    tagline: 'Chaque fin de saison soulève plus de questions.',
    accentColor: '#6c3483', featured: false, showInNav: true,
    timeOfDay: ['evening', 'night'],
  },
  {
    id: 'series-guerre', label: 'Séries Guerre & Politique', emoji: '🌍',
    type: 'genre', contentType: 'series',
    params: { genre: '10768' }, group: 'series', weight: 8,
    tagline: 'Le pouvoir corrompt. La série le prouve.',
    accentColor: '#546e7a', featured: false, showInNav: true,
  },
  {
    id: 'series-doc', label: 'Docu-séries', emoji: '🎬',
    type: 'genre', contentType: 'series',
    params: { genre: '99' }, group: 'series', weight: 9,
    tagline: 'Des vérités qui prennent des saisons à révéler.',
    accentColor: '#2ecc71', featured: false, showInNav: true,
    timeOfDay: ['morning', 'afternoon'],
  },
  {
    id: 'series-realite', label: 'Téléréalité', emoji: '📺',
    type: 'genre', contentType: 'series',
    params: { genre: '10764' }, group: 'series', weight: 10,
    tagline: 'La vraie vie est parfois plus folle que tout.',
    accentColor: '#00bcd4', featured: false, showInNav: false,
  },
  {
    id: 'series-famille', label: 'Séries Famille', emoji: '👨‍👩‍👧',
    type: 'genre', contentType: 'series',
    params: { genre: '10751' }, group: 'series', weight: 11,
    tagline: 'Pour regarder ensemble, épisode après épisode.',
    accentColor: '#e84393', featured: false, showInNav: false,
    timeOfDay: ['afternoon'],
    dayOfWeek: ['weekend'],
  },

  {
    id: 'kdrama', label: 'K-Drama', emoji: '🇰🇷',
    type: 'language', contentType: 'series',
    params: { language: 'ko' }, group: 'monde', weight: 1,
    tagline: 'Tu vas pleurer. Et tu voudras la suite.',
    accentColor: '#c0392b', featured: true, showInNav: true,
    timeOfDay: ['evening', 'night'],
    dayOfWeek: ['weekend'],
  },
  {
    id: 'anime-jp', label: 'Animé japonais', emoji: '🇯🇵',
    type: 'language', contentType: 'series',
    params: { language: 'ja' }, group: 'monde', weight: 2,
    tagline: "Des mondes qui n'existent nulle part ailleurs.",
    accentColor: '#e74c3c', featured: true, showInNav: true,
  },
  {
    id: 'bollywood', label: 'Bollywood', emoji: '🇮🇳',
    type: 'language', contentType: 'movie',
    params: { language: 'hi' }, group: 'monde', weight: 3,
    tagline: "Couleurs, danses, émotions à l'état brut.",
    accentColor: '#f39c12', featured: true, showInNav: true,
  },
  {
    id: 'cinema-fr', label: 'Cinéma français', emoji: '🇫🇷',
    type: 'language', contentType: 'movie',
    params: { language: 'fr' }, group: 'monde', weight: 4,
    tagline: "L'art de raconter avec peu et dire beaucoup.",
    accentColor: '#3498db', featured: true, showInNav: true,
    timeOfDay: ['afternoon', 'evening'],
  },
  {
    id: 'cinema-es', label: 'Cinéma espagnol', emoji: '🇪🇸',
    type: 'language', contentType: 'movie',
    params: { language: 'es' }, group: 'monde', weight: 5,
    tagline: 'Passion, drame et soleil dans chaque plan.',
    accentColor: '#e74c3c', featured: false, showInNav: true,
  },
  {
    id: 'cinema-it', label: 'Cinéma italien', emoji: '🇮🇹',
    type: 'language', contentType: 'movie',
    params: { language: 'it' }, group: 'monde', weight: 6,
    tagline: 'La dolce vita sur grand écran.',
    accentColor: '#27ae60', featured: false, showInNav: true,
  },
  {
    id: 'cinema-tr', label: 'Cinéma turc', emoji: '🇹🇷',
    type: 'language', contentType: 'series',
    params: { language: 'tr' }, group: 'monde', weight: 7,
    tagline: "Des séries qui durent des heures et dont on ne décroche pas.",
    accentColor: '#e74c3c', featured: false, showInNav: true,
  },
  {
    id: 'cinema-br', label: 'Cinéma brésilien', emoji: '🇧🇷',
    type: 'language', contentType: 'movie',
    params: { language: 'pt' }, group: 'monde', weight: 8,
    tagline: 'La chaleur du Brésil dans chaque image.',
    accentColor: '#27ae60', featured: false, showInNav: true,
  },
  {
    id: 'cinema-cn', label: 'Cinéma chinois', emoji: '🇨🇳',
    type: 'language', contentType: 'movie',
    params: { language: 'zh' }, group: 'monde', weight: 9,
    tagline: 'Poésie visuelle et épopées millénaires.',
    accentColor: '#e74c3c', featured: false, showInNav: true,
  },
  {
    id: 'cinema-ir', label: 'Cinéma iranien', emoji: '🇮🇷',
    type: 'language', contentType: 'movie',
    params: { language: 'fa' }, group: 'monde', weight: 10,
    tagline: 'Le cinéma le plus primé dont on parle le moins.',
    accentColor: '#c0392b', featured: true, showInNav: true,
  },
  {
    id: 'nollywood', label: 'Nollywood', emoji: '🌍',
    type: 'language', contentType: 'movie',
    params: { language: 'yo' }, group: 'monde', weight: 11,
    tagline: 'Le cinéma africain qui conquiert le monde.',
    accentColor: '#e67e22', featured: true, showInNav: true,
  },
  {
    id: 'cinema-pl', label: 'Cinéma polonais', emoji: '🇵🇱',
    type: 'language', contentType: 'movie',
    params: { language: 'pl' }, group: 'monde', weight: 12,
    tagline: 'Kieslowski, Polanski — une école unique.',
    accentColor: '#e74c3c', featured: false, showInNav: false,
  },
  {
    id: 'cinema-sv', label: 'Cinéma scandinave', emoji: '🇸🇪',
    type: 'language', contentType: 'movie',
    params: { language: 'sv' }, group: 'monde', weight: 13,
    tagline: 'Sombre, froid, et absolument captivant.',
    accentColor: '#2980b9', featured: false, showInNav: true,
    seasons: ['autumn', 'winter'],
  },
  {
    id: 'cinema-gr', label: 'Cinéma grec', emoji: '🇬🇷',
    type: 'language', contentType: 'movie',
    params: { language: 'el' }, group: 'monde', weight: 14,
    tagline: 'Yorgos Lanthimos a changé les règles.',
    accentColor: '#2980b9', featured: false, showInNav: false,
  },
  {
    id: 'cinema-ro', label: 'Cinéma roumain', emoji: '🇷🇴',
    type: 'language', contentType: 'movie',
    params: { language: 'ro' }, group: 'monde', weight: 15,
    tagline: 'La nouvelle vague qui secoue les festivals.',
    accentColor: '#e74c3c', featured: false, showInNav: false,
  },
  {
    id: 'cinema-vi', label: 'Cinéma vietnamien', emoji: '🇻🇳',
    type: 'language', contentType: 'movie',
    params: { language: 'vi' }, group: 'monde', weight: 16,
    tagline: 'Des images qui portent toute une mémoire.',
    accentColor: '#e74c3c', featured: false, showInNav: false,
  },

  {
    id: 'superheroes', label: 'Super-héros', emoji: '🦸',
    type: 'keyword', contentType: 'movie',
    params: { keyword: '9715' }, group: 'subgenres', weight: 1,
    tagline: 'Des pouvoirs, des combats, un destin.',
    accentColor: '#e63946', featured: true, showInNav: true,
    timeOfDay: ['afternoon', 'evening'],
  },
  {
    id: 'espionnage', label: 'Espionnage', emoji: '🕵️',
    type: 'keyword', contentType: 'movie',
    params: { keyword: '10717' }, group: 'subgenres', weight: 2,
    tagline: "Personne n'est vraiment qui il prétend être.",
    accentColor: '#2c3e50', featured: true, showInNav: true,
  },
  {
    id: 'survie', label: 'Survie', emoji: '🌿',
    type: 'keyword', contentType: 'movie',
    params: { keyword: '10183' }, group: 'subgenres', weight: 3,
    tagline: "Jusqu'où tu irais pour survivre ?",
    accentColor: '#27ae60', featured: true, showInNav: true,
  },
  {
    id: 'zombie', label: 'Zombie', emoji: '🧟',
    type: 'keyword', contentType: 'movie',
    params: { keyword: '12377' }, group: 'subgenres', weight: 4,
    tagline: "La fin du monde n'a jamais été aussi fun.",
    accentColor: '#8b0000', featured: false, showInNav: true,
    timeOfDay: ['night', 'late-night'],
  },
  {
    id: 'vampire', label: 'Vampire', emoji: '🧛',
    type: 'keyword', contentType: 'movie',
    params: { keyword: '10714' }, group: 'subgenres', weight: 5,
    tagline: "L'obscurité a toujours été séduisante.",
    accentColor: '#6c0000', featured: false, showInNav: true,
    timeOfDay: ['night', 'late-night'],
  },
  {
    id: 'time-travel', label: 'Voyage temporel', emoji: '⏱️',
    type: 'keyword', contentType: 'movie',
    params: { keyword: '4379' }, group: 'subgenres', weight: 6,
    tagline: 'Et si tu pouvais tout changer ?',
    accentColor: '#4361ee', featured: true, showInNav: true,
  },
  {
    id: 'ia', label: 'Intelligence Artificielle', emoji: '🤖',
    type: 'keyword', contentType: 'movie',
    params: { keyword: '310093' }, group: 'subgenres', weight: 7,
    tagline: 'Quand la machine commence à penser.',
    accentColor: '#4361ee', featured: true, showInNav: true,
  },
  {
    id: 'mafia', label: 'Mafia & Gangsters', emoji: '🎩',
    type: 'keyword', contentType: 'movie',
    params: { keyword: '11130' }, group: 'subgenres', weight: 8,
    tagline: 'Le pouvoir. La trahison. La famille.',
    accentColor: '#2c3e50', featured: true, showInNav: true,
    timeOfDay: ['evening', 'night'],
  },
  {
    id: 'serial-killer', label: 'Serial Killer', emoji: '🔪',
    type: 'keyword', contentType: 'movie',
    params: { keyword: '10341' }, group: 'subgenres', weight: 9,
    tagline: "L'esprit humain dans ses recoins les plus sombres.",
    accentColor: '#1a1a1a', featured: false, showInNav: true,
    timeOfDay: ['night', 'late-night'],
  },
  {
    id: 'arts-martiaux', label: 'Arts martiaux', emoji: '🥋',
    type: 'keyword', contentType: 'movie',
    params: { keyword: '1568' }, group: 'subgenres', weight: 10,
    tagline: 'Le corps comme arme absolue.',
    accentColor: '#e63946', featured: false, showInNav: true,
  },
  {
    id: 'prison', label: 'Prison', emoji: '🔒',
    type: 'keyword', contentType: 'movie',
    params: { keyword: '818' }, group: 'subgenres', weight: 11,
    tagline: 'Quand les murs se referment sur toi.',
    accentColor: '#7f8c8d', featured: false, showInNav: true,
    timeOfDay: ['night', 'late-night'],
  },
  {
    id: 'fantomes', label: 'Fantômes', emoji: '👻',
    type: 'keyword', contentType: 'movie',
    params: { keyword: '10265' }, group: 'subgenres', weight: 12,
    tagline: "Certains ne savent pas encore qu'ils sont partis.",
    accentColor: '#6c3483', featured: false, showInNav: true,
    timeOfDay: ['night', 'late-night'],
  },
  {
    id: 'pirates', label: 'Pirates', emoji: '🏴‍☠️',
    type: 'keyword', contentType: 'movie',
    params: { keyword: '1318' }, group: 'subgenres', weight: 13,
    tagline: 'La mer, le rhum et la liberté.',
    accentColor: '#2980b9', featured: false, showInNav: false,
  },
  {
    id: 'found-footage', label: 'Found Footage', emoji: '📹',
    type: 'keyword', contentType: 'movie',
    params: { keyword: '14796' }, group: 'subgenres', weight: 14,
    tagline: 'Tu regardes. Mais quelqu\'un te regarde aussi.',
    accentColor: '#1a1a1a', featured: false, showInNav: false,
    timeOfDay: ['night', 'late-night'],
  },
  {
    id: 'jeux-mortels', label: 'Jeux mortels', emoji: '🎮',
    type: 'keyword', contentType: 'movie',
    params: { keyword: '1299' }, group: 'subgenres', weight: 15,
    tagline: "Les règles sont simples. Mourir ne l'est pas.",
    accentColor: '#8b0000', featured: true, showInNav: true,
    timeOfDay: ['night', 'late-night'],
  },
  {
    id: 'apocalypse', label: 'Apocalypse', emoji: '🌋',
    type: 'keyword', contentType: 'movie',
    params: { keyword: '157927' }, group: 'subgenres', weight: 16,
    tagline: 'Après la fin, que reste-t-il ?',
    accentColor: '#e63946', featured: true, showInNav: true,
  },
  {
    id: 'dystopie', label: 'Dystopie', emoji: '🏚️',
    type: 'keyword', contentType: 'movie',
    params: { keyword: '155202' }, group: 'subgenres', weight: 17,
    tagline: 'Des sociétés brisées que tu reconnaîtras.',
    accentColor: '#7f8c8d', featured: true, showInNav: true,
  },
  {
    id: 'vrai-histoire', label: 'Basé sur une histoire vraie', emoji: '📰',
    type: 'keyword', contentType: 'movie',
    params: { keyword: '9840' }, group: 'subgenres', weight: 18,
    tagline: "Ça s'est vraiment passé. C'est ça le plus fou.",
    accentColor: '#27ae60', featured: true, showInNav: true,
  },

  {
    id: 'lgbt', label: 'LGBTQ+', emoji: '🏳️‍🌈',
    type: 'keyword', contentType: 'both',
    params: { keyword: '158718' },
    group: 'representation', weight: 1,
    tagline: "Des histoires qui méritaient d'être racontées.",
    accentColor: '#9b59b6', featured: true, showInNav: true,
  },
  {
    id: 'feminisme', label: 'Féminisme', emoji: '✊',
    type: 'keyword', contentType: 'both',
    params: { keyword: '10133' },
    group: 'representation', weight: 3,
    tagline: "Des femmes qui ont refusé d'attendre.",
    accentColor: '#e91e8c', featured: true, showInNav: true,
  },
  {
    id: 'afro-american', label: 'Cinéma afro-américain', emoji: '✊🏿',
    type: 'keyword', contentType: 'movie',
    params: { keyword: '10503' },
    group: 'representation', weight: 4,
    tagline: 'Des voix longtemps réduites au silence.',
    accentColor: '#e67e22', featured: true, showInNav: true,
  },

  {
    id: 'action-scifi', label: 'Action Sci-Fi', emoji: '🚀',
    type: 'combo', contentType: 'movie',
    params: { genre: '28,878' }, group: 'editorial', weight: 1,
    tagline: 'Le futur se combat les poings en avant.',
    accentColor: '#4361ee', featured: true, showInNav: false,
    timeOfDay: ['afternoon', 'evening'],
  },
  {
    id: 'comedie-roman', label: 'Comédie romantique', emoji: '💑',
    type: 'combo', contentType: 'movie',
    params: { genre: '35,10749' }, group: 'editorial', weight: 2,
    tagline: 'Rire et tomber amoureux en même temps.',
    accentColor: '#e91e8c', featured: true, showInNav: false,
    timeOfDay: ['evening'],
    dayOfWeek: ['weekend'],
  },
  {
    id: 'thriller-psy', label: 'Thriller psychologique', emoji: '🧠',
    type: 'combo', contentType: 'movie',
    params: { genre: '53,18' }, group: 'editorial', weight: 3,
    tagline: 'Pour les esprits qui aiment être dérangés.',
    accentColor: '#c0392b', featured: true, showInNav: false,
    timeOfDay: ['evening', 'night'],
  },
  {
    id: 'horreur-surnat', label: 'Horreur surnaturel', emoji: '👁️',
    type: 'combo', contentType: 'movie',
    params: { genre: '27,14' }, group: 'editorial', weight: 4,
    tagline: "Quand la peur vient de l'au-delà.",
    accentColor: '#6c0000', featured: false, showInNav: false,
    timeOfDay: ['night', 'late-night'],
  },
  {
    id: 'drame-histo', label: 'Drame historique', emoji: '⚔️',
    type: 'combo', contentType: 'movie',
    params: { genre: '18,36' }, group: 'editorial', weight: 5,
    tagline: "L'histoire a toujours besoin de témoins.",
    accentColor: '#1a5276', featured: false, showInNav: false,
  },
  {
    id: 'crime-thriller', label: 'Crime Thriller', emoji: '🔫',
    type: 'combo', contentType: 'movie',
    params: { genre: '80,53' }, group: 'editorial', weight: 6,
    tagline: 'Quand le crime et la tension fusionnent.',
    accentColor: '#2c3e50', featured: false, showInNav: false,
    timeOfDay: ['evening', 'night'],
  },
  {
    id: 'comedie-noire', label: 'Comédie noire', emoji: '🖤',
    type: 'combo', contentType: 'movie',
    params: { genre: '35,80' }, group: 'editorial', weight: 7,
    tagline: "Rire de ce qu'on ne devrait pas. C'est ça.",
    accentColor: '#1a1a1a', featured: true, showInNav: false,
    timeOfDay: ['night', 'late-night'],
  },
  {
    id: 'guerre-drame', label: 'Guerre & Drame', emoji: '🎖️',
    type: 'combo', contentType: 'movie',
    params: { genre: '10752,18' }, group: 'editorial', weight: 8,
    tagline: 'Derrière chaque bataille, une histoire humaine.',
    accentColor: '#7f8c8d', featured: false, showInNav: false,
  },

  {
    id: 'ere-muet', label: 'Cinéma muet', emoji: '🎞️',
    type: 'era', contentType: 'movie',
    params: { year_lte: '1929' }, group: 'epoque', weight: 1,
    tagline: 'Avant les mots, il y avait les images.',
    accentColor: '#7f8c8d', featured: false, showInNav: false,
  },
  {
    id: 'annees-50', label: 'Années 50', emoji: '📽️',
    type: 'era', contentType: 'movie',
    params: { year_gte: '1950', year_lte: '1959' }, group: 'epoque', weight: 2,
    tagline: "L'âge d'or d'Hollywood.",
    accentColor: '#7f8c8d', featured: false, showInNav: false,
  },
  {
    id: 'annees-60', label: 'Années 60', emoji: '🌸',
    type: 'era', contentType: 'movie',
    params: { year_gte: '1960', year_lte: '1969' }, group: 'epoque', weight: 3,
    tagline: 'La Nouvelle Vague. La révolution.',
    accentColor: '#f39c12', featured: false, showInNav: false,
  },
  {
    id: 'annees-70', label: 'Années 70', emoji: '🕺',
    type: 'era', contentType: 'movie',
    params: { year_gte: '1970', year_lte: '1979' }, group: 'epoque', weight: 4,
    tagline: 'New Hollywood. Les auteurs prenaient les commandes.',
    accentColor: '#e67e22', featured: false, showInNav: false,
  },
  {
    id: 'annees-80', label: 'Années 80', emoji: '📼',
    type: 'era', contentType: 'movie',
    params: { year_gte: '1980', year_lte: '1989' }, group: 'epoque', weight: 5,
    tagline: 'Avant les smartphones, après le disco.',
    accentColor: '#9b59b6', featured: true, showInNav: true,
    seasons: ['autumn', 'winter'],
  },
  {
    id: 'annees-90', label: 'Années 90', emoji: '💿',
    type: 'era', contentType: 'movie',
    params: { year_gte: '1990', year_lte: '1999' }, group: 'epoque', weight: 6,
    tagline: 'Tarantino. Kubrick. Le cinéma indie explosait.',
    accentColor: '#e67e22', featured: true, showInNav: true,
  },
  {
    id: 'annees-2000', label: 'Années 2000', emoji: '📱',
    type: 'era', contentType: 'movie',
    params: { year_gte: '2000', year_lte: '2009' }, group: 'epoque', weight: 7,
    tagline: 'Le tournant numérique du cinéma.',
    accentColor: '#3498db', featured: false, showInNav: true,
  },
  {
    id: 'annees-2010', label: 'Années 2010', emoji: '📲',
    type: 'era', contentType: 'movie',
    params: { year_gte: '2010', year_lte: '2019' }, group: 'epoque', weight: 8,
    tagline: 'La décennie des univers étendus.',
    accentColor: '#2980b9', featured: false, showInNav: true,
  },
  {
    id: 'recents', label: 'Sorties récentes', emoji: '🆕',
    type: 'era', contentType: 'movie',
    params: { year_gte: '2023' }, group: 'epoque', weight: 9,
    tagline: 'Ce que tout le monde regarde en ce moment.',
    accentColor: '#27ae60', featured: true, showInNav: true,
    timeOfDay: ['afternoon', 'evening'],
  },
];

export const ALL_GROUPS = [
  { key: 'films',          label: 'Films',                  emoji: '🎬', description: 'Tous les genres du cinéma mondial'     },
  { key: 'series',         label: 'Séries',                 emoji: '📺', description: 'Les meilleures séries par genre'       },
  { key: 'monde',          label: 'Cinémas du monde',       emoji: '🌍', description: 'Explorez le cinéma de chaque culture'  },
  { key: 'subgenres',      label: 'Sous-genres',            emoji: '🎭', description: 'Les catégories que personne ne propose'},
  { key: 'representation', label: 'Représentation',         emoji: '🏳️‍🌈', description: 'Des histoires pour tout le monde'   },
  { key: 'editorial',      label: 'Sélections éditoriales', emoji: '✨', description: 'Nos combinaisons de genres préférées'  },
  { key: 'epoque',         label: 'Par époque',             emoji: '⏳', description: 'Voyagez dans le temps du cinéma'       },
] as const;

export const getCategoryGroup = (group: string): Category[] =>
  CATEGORIES.filter(c => c.group === group)
             .sort((a, b) => a.weight - b.weight);

export const getCategoryById = (id: string): Category | undefined =>
  CATEGORIES.find(c => c.id === id);

export const getFeaturedCategories = (): Category[] =>
  CATEGORIES.filter(c => c.featured)
             .sort((a, b) => a.weight - b.weight);

export const getNavCategories = (): Category[] =>
  CATEGORIES.filter(c => c.showInNav);
